from Function import Init
class Test:
    def test(self):
        cla = Init()
        cla.analiz('CREATE cars ( id NOMER, name Marka, name Contry ,id  price ,name kilkist);')
        cla.analiz('INSERT INTO cars ( " 1 ", " Mazda ", " Ukraine " , " 10200 " , " 4000 ");')
        cla.analiz('INSERT INTO cars ( " 2 ", " Mazda ", " Ukraine " , " 10500 " , " 3000 ");')
        cla.analiz('INSERT INTO cars ( " 3 ", " Nissan ", " Ukraine " , " 10100 " , " 10520 ");')
        cla.analiz('INSERT INTO cars ( " 4 ", " Nissan ", " Ukraine " , " 15200 " , " 100 ");')
        cla.analiz("SELECT * FROM ' cars ';")
        cla.analiz('DELETE cars WHERE Marka = "Mazda";')
        cla.analiz("SELECT * FROM ' cars ';")
        cla.analiz("SELECT * FROM ' cars ' NOMER Marka")
        cla.analiz("SELECT * FROM ' cars ' NOMER")
        cla.analiz("SELECT * FROM ' cars ' price")
        cla.analiz("SELECT * FROM ' cars ' price kilkist")
        cla.analiz("SELECT FROM ' cars ' Marka Contry WHERE Marka = Nissa ")
        cla.analiz('INSERT INTO cars ( " 2 ", " Mazda ", " Ukraine " , " 10500 " , " 2500 ");')
        cla.analiz("SELECT * FROM ' cars ';")
        cla.analiz("SELECT FROM ' cars ' Marka Contry WHERE Marka = Mazda ")
        cla.analiz('INSERT INTO cars ( " 3 ", " Nissan ", " Golandia " , " 10100 " , " 12020 ");')
        cla.analiz('INSERT INTO cars ( " 3 ", " Nissan ", " Amsterdam " , " 10100 " , " 13020 ");')
        cla.analiz("SELECT * FROM ' cars ';")
        cla.analiz("SELECT FROM ' cars ' Marka Contry kilkist WHERE Marka = Nissan GROUP_BY kilkist;")
        cla.analiz("SELECT FROM ' cars ' Marka Contry kilkist WHERE Marka = Nissan GROUP_BY Contry;")
te=Test()
te.test()